# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy all source code
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (not strictly required for stdio based MCP, but left for any TCP-based usage)
# EXPOSE 3000

CMD ["node", "build/index.js"]
